# vim:ft=tmux:fdm=marker:

# Colors {{{
    source-file ~/documents/dotfiles/tmux.d/colors/solarized-dark
# }}}
# Mouse {{{
    set -g mode-mouse on
    set -g mouse-select-pane on
    set -g mouse-resize-pane on
    set -g mouse-select-window on
# }}}
