#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24
PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"


unique() {
    if which stdbuf; then
        stdbuf -oL uniq
    else
        while read -r line; do
            if [ "$line" != "$old_line" ]; then
                old_line="$line"
                printf "%s\n" "$line"
            fi
        done
    fi
}

ensure_fifo() {
    if [ ! -e "$PANEL_FIFO" ] || [ -p "$PANEL_FIFO" ]; then
        rm -f "$PANEL_FIFO"
        mkfifo "$PANEL_FIFO"
    else
        echo "$PANEL_FIFO exists and is not a fifo" >&2
        exit 1
    fi
}

clock() {
    fmt=${1:-'%a %H:%M'}
    while sleep 1; do
        date +"C$fmt"
    done
}

deadbeef_track() {
    fmt=${1:-'%a - %t'}
    while sleep 1; do
        info="$(deadbeef --nowplaying "$fmt" 2>/dev/null)"
        if [ "$info" = nothing ]; then
            info=''
        fi
        echo "P$info"
    done | unique
}


if pgrep -cx panel; then
    echo "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

ensure_fifo

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe  >"$PANEL_FIFO" &
xtitle -sf 'T%s\n'        >"$PANEL_FIFO" &
deadbeef_track            >"$PANEL_FIFO" &
clock                     >"$PANEL_FIFO" &
# conky -c ~/.config/bspwm/conkyrc > "$PANEL_FIFO" &

. ~/.config/bspwm/colors.sh

cat "$PANEL_FIFO" \
    | ~/.config/bspwm/panel-renderer \
    | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY"     \
               -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" \
    | sh &

wait
